### ISSUE TITLE
provide feedback on download fail

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#122]
When tryin to download a zip archive from the item page, if there is no file a blank page is shown, look to provide details

**Comment by VermaBSI** [comment]
I can't actually test this because can't find any examples now in the UAT system where the zip file isn't downloading (including those currently at stage 0.99). I also tried manually adding a UPI that would deliberately fail the data validation/isn't PUBL yet into the system so it wouldn't find a file to collate, but that didn't work and wouldn't I guess because it wouldn't even try to make a collation for anything data invalid/not yet PUBL.

**Comment by ben-garside** [comment]
Thanks for looking in to this, yeah going to be hard to test as it should never really happen :) I have been able to test this, and can confirm that the error message is being displayed when the zip file is not available.

Going to close if that's OK with you @VermaBSI?

**Comment by VermaBSI** [comment]
Yes okay, go ahead :)
