### ISSUE TITLE
Create UAT/PROD split for sendItems.php

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#33]
Update code to allow PRD to send to test FTP and email only to internal users, should mirror with PROD but PROD points at external resources

**Comment by VermaBSI** [comment]
I think you mean 'Update  code to allow UAT...'
I haven't done a send off UAT without  your manual co-operation yet, if this is what needs to happen to sign this off. We'll be doing a send this Friday as agreed.

**Comment by odeclas** [comment]
This issue was to allow for full end-to-end testing of the collation and send process.

The same behaviour needs to exist on UAT and PROD, but the destination for the FTP send, and a minor alteration to the email (subject) needs to be done.

So the ticket can be closed if UAT is sending to test, and PROD is sending to live. If we haven't done a PROD send, then no.

**Comment by VermaBSI** [comment]
Understood - but I don't know if the 'sending to test' in UAT is happening yet without having to tell Ben that 'I've set a bunch of items to 10.20 - please FTP to test'. Was going to find this out on Friday. 

I believe PROD is sending 10.20s automatically to live, as it did for a send I did when Ben was away.
