### ISSUE TITLE
Agree scheduled send time

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#46]
XCP team need to agree the (daily) scheduled send time.

To be discussed at next XML meeting.

**Comment by ben-garside** [comment]
task schedule is ready one the timings have been agreed.

**Comment by VermaBSI** [comment]
Hi Ben - I will discuss this with my team, but just a quick note to say I noticed XCP did a send automatically last Friday evening when I set something to 10.20 whilst you were away (email to Innodata was 1800 hrs). It was just one UPI, but it did do it correctly and everything. But we can still set a time to keep checking before we sign off the sending process - that would be 4pm to check all collations and 5pm for it to run the send, every Friday.
I've noticed PROD env is now not seeing any new collations - only UAT env is, as the 'Live' site for now. I have claimed all new ones in since last send, but I am seeing a problem in trying to check them. I am away this afternoon so we'll probably have to re-visit the sending of these early next week if possible please.

**Comment by ben-garside** [comment]
Sorry about the automatic sends, it was a mistake and the process was disabled as soon as I noticed. I forgot to disable once I set up the process.

UAT is not the Live site at all and should not be treated as such the PRD server will ALWAYS be the live site (xcp.cs) UAT is only ever for testing releases.

If PRD is not reciving content, this is a problem :worried: and something to look in to, would you mind raising an issue for it with some examples of what should be in the system etc.?

Cheers.

**Comment by VermaBSI** [comment]
Yes sure, will do.

Re: The issue about not being able to check the most recent collated zips in UAT - do you want to deal with this when we do this week's send this Friday? Should I raise this as a new issue now in any case?

**Comment by ben-garside** [comment]
Sorry I think I misunderstood. When you said: _PROD env is now not seeing any new collations - only UAT_ are you talking about when you click to download the zip on the overview page? or that they are not showing up in the Activity Tracker?

**Comment by VermaBSI** [comment]
I mean that they are not showing up in PROD Activity Tracker, so they're not even in any list. (Just raised issue #57 about this. The issue about not being able to download the zip to check is another issue in UAT at the moment).

**Comment by ben-garside** [comment]
This is now part of #69
