### ISSUE TITLE
Creation of 10:19 Draft Send

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#69]
As per email conversation, while we bed XCP in Varun has requested a final gate before sending on PROD. This solution gives us a solution which may prove useful longterm too, and gives the user the option to Draft Send prior to Send.

Functionality request is to re-use a copy of the script currently executing for 10:20 Ready to Send @ 5pm but with these differences:
1.	It will look for items at 10:19
2.	It will run at a different time (4pm unless told otherwise)
3.	It will send the manifest to content.operations with ‘Draft – xxxx’ in the subject line
4.	It will send the content to the test FTP site
5.	It will move the record on to 10:20 instead of 20:00

**Comment by ben-garside** [comment]
#46

**Comment by VermaBSI** [comment]
Hi Ben,

I will test this when I get round to sending this week - at the moment there is no data in UAT to work with.

**Comment by ben-garside** [comment]
Sorry i should have told you about this, i have set this up to run at 4 and 5 as it will in prod but currently both are set to FTP to the test server and emails are only internal, so you can still test with dummy data.

**Comment by VermaBSI** [comment]
Hello :)

So I did a test of this in UAT today as follows:

Set the following UPIs to 10.19 shortly after 3pm today:
30047368 (p2)
30047368 (p8)
30256178 (p7)
30256178 (p8)
30260135 (p2) *
30260135 (p8) *

Result after 4pm:
- No dummy-send email notification
- System moved UPIs to stage 10.20 and into the UNCLAIMED list (keeping in the Collation tab) - except those marked with * above (stayed at 10.19). 
- Nothing FTPed to Test site (no folder dated today found)

Result after 5pm:
Nothing changed since result after 4pm above.

**Comment by ben-garside** [comment]
OK, i know what the issue was after a lot of investigation and have just run some tests and it looks to be ok now. I am going to run another test on UAT so ignore any emails you might get...

**Comment by VermaBSI** [comment]
So I did a test of this in UAT again today as follows:

Set the following UPIs to 10.19 shortly after 3pm today:
30298672 (p1)
 30297755 (p4)
 30297755 (p8)
 30269842 (p2)
 30269842 (p8) 
 30264426 (p4) 
30264426 (p8)
30264414 (p2)
30264414 (p8)

Result after 4pm:
• Dummy-send email notification and attached transmission sheet - all correct
•System moved UPIs to stage 10.20 and into the UNCLAIMED list (keeping in the Collation tab) - all correct 
•The folder with today's date in the Test FTP (checked both) did NOT have any correct files at all reflecting the above list/contents of the transmission sheet.

Result after 5pm:
• Real-send email notification and attached transmission sheet - all correct
•System moved UPIs to stage 20.00 and into the UNCLAIMED list in the Conversion tab - all correct 
•The folder with today's date in the Test FTP (checked both) did NOT have any correct files at all reflecting the above list/contents of the transmission sheet.

**Comment by VermaBSI** [comment]
Also. when the 4pm round moves UPIs to 10.20 could it keep them in the CLAIMED list please?

**Comment by ben-garside** [comment]
raised as request #91

**Comment by ben-garside** [comment]
The above is due to the fact that we did a test LIVE send on friday as well, so the files that we sent via the manual test have overwritten the ones that were placed there by the automated UAT send.

I will create some new FTP sites to avoid this in future. I will send the details to you via email shortly. Please can you set up for another test?

**Comment by VermaBSI** [comment]
Hi Ben - was going to conduct another test today in UAT for this, but can't see any data in UAT when I log in as me.

**Comment by ben-garside** [comment]
please try again now

**Comment by VermaBSI** [comment]
Just making a record of what I set to 10.19 so can easily check which ones should have been FTPed and set to 10.20 (please ignore):

30270463	10.19
30276374	10.19
30297353	10.19
30298804	10.19
30331419        10.19
30234058        10.19

**Comment by VermaBSI** [comment]
So the test I did today completely worked through to real send (10.19 to 20.00) - good going Ben :)!

Of course though, owing to issue #73, half the zips are empty so would not have made it to 20.00 in real life. That's why I checked also that  if something faulty was accidentally set at 10.19 it could be put back to 10.10 before it made it to 10.20 (perhaps I should test if something made it to 10.20 accidentally it could also be pushed back again...).

One last observation is that you can't set p8 items to 10.19 - it would be helpful if you could too so the 10.19 trial is all-inclusive as a mimicry of the real send. 

Many thanks!

**Comment by ben-garside** [comment]
That's great news, I am going to mark this as closed.

If you think that the system should maybe have a check to make sure that there are no errors in the collation before doing any sends lets open up another issue for that and talk about it there.

As for setting pl8s to 10:19 - you will have to set it in the configuration.

**Comment by VermaBSI** [comment]
Hi Ben,

The stage 10.19 appears to no longer exist in UAT - can't select 10.19 for any item and can't find it as a stage to adjust the rules for PL8 in the Stage Manager.

Was planning on doing another send tomorrow/Wed.

Thanks

**Comment by ben-garside** [comment]
@odeclas has been working on the stages ect. in UAT so might have deleted it? you just need to create it again in the system ``Manage > Stage Manager > Add Stage``
