### ISSUE TITLE
add batch id when sending an item

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#90]

**Comment by VermaBSI** [comment]
Hi this worked with the last test send I did on 27/01/2016.

The only small glitch is that in the item's detail page the batch data appears under Item Data as **Innodata_Batch_ID** instead of under Batch Data. This isn't really a problem. 

But the main eventuality is that we would be able to add TAT and cost data at batch level, and filter for items per Innodata_Batch_ID.

**Comment by ben-garside** [comment]
the batch ID is actually stored as item data not batch data, so this is to be expected.

Closing issue :)
